version: '3.8'

services:
  db:
    image: postgres:13
    container_name: postgres-container
    restart: always
    environment:
      POSTGRES_DB: carts
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    networks:
      - myapp-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    networks:
      - myapp-network

networks:
  myapp-network:
    driver: bridge
